[package]
name = "useless-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde_json = "1.0.132"
tokio = {version= "1.41.1",features=["full"]}
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
